GET https://1ced2a8f3211.up.railway.app/api/students

###

GET http://localhost:3000/api/students/6114aca821104f3ac4d09c1c

###

POST https://1ced2a8f3211.up.railway.app/api/students
Content-Type: application/json

{
    "name": "someone",
    "roll": 36,
    "present": true
}

###

PUT https://1ced2a8f3211.up.railway.app/api/students/6114b42d24450a001b9aa64d
Content-Type: application/json

{
    "name": "the new ninja",
    "roll": 29,
    "present": false
}

###

DELETE https://1ced2a8f3211.up.railway.app/api/students/6114b42d24450a001b9aa64d
