GET https://express-student-api-production.up.railway.app/api/students

###

GET https://express-student-api-production.up.railway.app/api/students6114aca821104f3ac4d09c1c

###

POST https://express-student-api-production.up.railway.app/api/students
Content-Type: application/json

{
    "name": "someone",
    "roll": 36,
    "present": true
}

###

PUT https://express-student-api-production.up.railway.app/api/students/6114b42d24450a001b9aa64d
Content-Type: application/json

{
    "name": "the new ninja",
    "roll": 29,
    "present": false
}

###

DELETE https://express-student-api-production.up.railway.app/api/students/6114b42d24450a001b9aa64d
